Новый эвей мишион, и чуть чуть для ерт там
CeladonSS13/Foundation-19 pull request #43
Opened 2024-04-20 18:31 UTC by lobzik8

2024-04-21 08:41 UTC, MysticalFaceLesS commented on code/game/antagonist/outsider/ert.dm
Требуется вынести в модуль. Либо частично, либо полностью. Лишнее не удалить, а закомментировать /* */

2024-05-04 18:28 UTC, MrCat15352 requested changes

2024-05-04 18:28 UTC, MrCat15352 commented on code/game/antagonist/outsider/ert.dm
Собственно, оформить нужно как в ридми mod_celadon написано. Добавить что ты сделал, айди поставить, закомментить оригинальный код. А собственно что именно тут ты сделал? @lobzik8

2024-05-04 18:28 UTC, MrCat15352 commented on code/modules/awaymissions/corpse.dm
Весь кор код комментить теперь не надо. И что тут ты менял? @lobzik8

2024-05-04 18:28 UTC, MrCat15352 commented on mod_celadon/__maps/site53/away_mission-1.dmm
У нас карты переместились. Тут надо решить конфликт тебе

2024-05-04 18:28 UTC, MrCat15352 commented on mod_celadon/_components/__components.dme
> -#endif
И на кой тебе черт удалять это? @lobzik8

2024-05-04 18:28 UTC, MrCat15352 commented on mod_celadon/_components/code/copse.dm
Опять же, у меня ВОПРОСЫ, ты менял тут ПРЯМ ВСЁ? @lobzik8

2024-05-04 18:28 UTC, MrCat15352 commented on mod_celadon/_components/code/ert.dm
Аналогично вышему

2024-05-11 12:44 UTC, closed without merging