Notebook
CeladonSS13/Foundation-19 pull request #58
Opened 2024-05-03 19:07 UTC by xhankaishi

ПР делает что-то умное. Исправлены ошибки, добавлены координаты цели для 096 (Спасибо огромное Сенсею), исправлен спрайт экрана ноутбука.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2024-05-04 18:20 UTC, MrCat15352 requested changes

2024-05-04 18:20 UTC, MrCat15352 commented on code/modules/SCP/SCPs/SCP-096.dm
> -#undef STATE_096_CHASING
Окей, но оформи пожалуйста согласно ридми модульности mod_celadon. А именно, добавь комментарии что это было удалено, айди модпака и место куда оно было перемещено

2024-05-04 18:20 UTC, MrCat15352 commented on code/modules/SCP/SCPs/SCP-096.dm
> +// #undef STATE_096_STAGGERED // Прерывание убрано для кода в -> mod_celadon\SCP096\code\SCP096.dm
Забудь, так не пишем больше

2024-05-04 18:35 UTC, xhankaishi commented on code/modules/SCP/SCPs/SCP-096.dm
> +// #undef STATE_096_STAGGERED // Прерывание убрано для кода в -> mod_celadon\SCP096\code\SCP096.dm
Как не пишем...

2024-05-04 18:35 UTC, xhankaishi commented on code/modules/SCP/SCPs/SCP-096.dm
> -#undef STATE_096_CHASING
Оно никуда не было перемещено... это прерывание макроса...

2024-05-04 18:55 UTC, xhankaishi commented on code/modules/SCP/SCPs/SCP-096.dm
> -#undef STATE_096_CHASING
тяжело...

2024-05-07 06:09 UTC, MrCat15352 requested changes

2024-05-07 06:09 UTC, MrCat15352 commented on code/modules/SCP/SCPs/SCP-096.dm
> -#undef STATE_096_CHASING
Мда, вот как надо было ->
```
// [CELADON-REMOVE] - CELADON_SCP_096 - Убираем прерывание в mod_celadon\SCP096\code\SCP096.dm
// #undef STATE_096_IDLE
#undef STATE_096_SCREAMING
// #undef STATE_096_CHASING
// [/CELADON-REMOVE]
```

2024-05-07 06:09 UTC, MrCat15352 commented on code/modules/SCP/SCPs/SCP-096.dm
> +// #undef STATE_096_STAGGERED // Прерывание убрано для кода в -> mod_celadon\SCP096\code\SCP096.dm
Вот так вот комментировать не надо -> ```// Прерывание убрано для кода в -> mod_celadon\SCP096\code\SCP096.dm```

2024-05-07 06:09 UTC, MrCat15352 commented on code/modules/modular_computers/computers/modular_computer/variables.dm
> +	var/icon_state_screensaver = "mod_celadon/laptop_rotate/icons/laptop_rotate_1.dmi/standby"
А вот тут надо было использовать EDIT, вот так ->
```
// [CELADON-EDIT] - CELADON_SCP_096
// var/icon_state_menu = "mod_celadon/laptop_rotate/icons/laptop_rotate.dmi/menu"							// Icon state overlay when the computer is turned on, but no program is loaded that would override the screen. // CELADON-EDIT - ORIGINAL
// var/icon_state_screensaver = "mod_celadon/laptop_rotate/icons/laptop_rotate.dmi/standby" // CELADON-EDIT - ORIGINAL
var/icon_state_menu = "mod_celadon/laptop_rotate/icons/laptop_rotate_1.dmi/menu"							// Icon state overlay when the computer is turned on, but no program is loaded that would override the screen.
var/icon_state_screensaver = "mod_celadon/laptop_rotate/icons/laptop_rotate_1.dmi/standby"
// [/CELADON-EDIT]
```


#undef STATE_096_SCREAMING
// #undef STATE_096_CHASING
// [/CELADON-REMOVE]

2024-05-07 06:09 UTC, MrCat15352 commented on mod_celadon/SCP096/README.md
Сюда тебе надо будет добавить инфу об EDIT с того файла

2024-05-11 12:40 UTC, MrCat15352 approved these changes

2024-05-11 12:40 UTC, MrCat15352 commented on code/modules/SCP/SCPs/SCP-096.dm
> +// #undef STATE_096_STAGGERED // Прерывание убрано для кода в -> mod_celadon\SCP096\code\SCP096.dm
Тут аналогично как выше сделать, или продолжи блок, до того момента где выпиливание заканчивается

2024-05-11 12:40 UTC, merged