Баунти, описание сцп
CeladonSS13/Foundation-19 pull request #63
Opened 2024-05-08 09:25 UTC by xhankaishi

Баунти, описание сцп при их выборе в меню become an SCP

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2024-05-08 09:49 UTC, MrCat15352 commented on mod_celadon/opisanie_scp/code/opisanie_scp.dm
> +/mob/living
Вот это и всё то внизу можно оставить тут. Всё что ты новое пишешь, не совпадающее и не пересекающееся с кор кодом - и будет являться модульным кодом. Как появятся новые СЦП, описание к ним, просто люди будут тут внизу дополнять кодом их.

2024-05-08 10:01 UTC, MrCat15352 requested changes

2024-05-08 10:01 UTC, MrCat15352 commented on mod_celadon/opisanie_scp/code/opisanie_scp.dm
> +/mob/observer/ghost/verb/become_scp()
Этот блок вернуть в кор код, в нем ты менял одну строку вроде как

2024-05-08 10:01 UTC, MrCat15352 commented on mod_celadon/opisanie_scp/_opisanie_scp.dm
> +/datum/modpack/opisanie_scp/pre_initialize() /// Эти конструкции нужны, для того чтобы в вашем модпаке что-то инициализировалось, до, после или вместе с модпаком.
Эти три инициализации удали, они тебе не нужны. В комментах же сказано, не пользуешься, удаляй)

2024-05-08 10:01 UTC, MrCat15352 commented on mod_celadon/opisanie_scp/_opisanie_scp.dm
> +	desc = "Описание сцп при выборе его через become an SCP. Баунти"
Слово баунти убирай. Зачем игрокам знать что это баунти?

2024-05-08 10:01 UTC, MrCat15352 commented on mod_celadon/opisanie_scp/README.md
> +- `code/__defines/~mods/opisanie_scp.dm`: `OPISANIE_SCP_SPEED_MULTIPLIER`, `OPISANIE_SCP_SPEED_BASE`
раз написал отсутствуют, то че это за строка?

2024-05-08 10:01 UTC, MrCat15352 commented on mod_celadon/opisanie_scp/README.md
> +- `mods/_master_files/code/my_modular_override.dm`: `proc/overriden_proc`, `var/overriden_var`
Ты же написал что отсутствуют...

2024-05-08 10:01 UTC, MrCat15352 commented on code/modules/mob/observer/ghost/ghost.dm
> +// 		var/agreement = tgui_alert(src, "Warning! SCPs are likley to spend a long amount of time within their containment chamber and are not guaranteed to be let out![(selected_scp.SCP.metaFlags & SCP_
Вот тут ты менял код, строчку одну. Возвращай кор код. И пиши вот так:
```
// [CELADON-EDIT] - DESCRIPTION_SCP - (тут комментарий если хочешь что-то написать)
// var/agreement = tgui_alert(src, "Warning! SCPs are likley to spend a long amount of time within their containment chamber and are not guaranteed to be let out![(selected_scp.SCP.metaFlags & SCP_ROLEPLAY) ? " Additionally, this is a roleplay oriented SCP. That means you are expected to behave like the SCP would in lore, and failing to do so would result in ban from playing roleplay SCPs." : ""]", "Are you sure?", list("Yes","No")) // CELADON-EDIT - ORIGINAL
var/agreement = tgui_alert(src, (selected_scp.opisanie ? selected_scp.opisanie : ""), "Are you sure?", list("Yes","No"))
// [/CELADON-EDIT]
```

2024-05-09 17:16 UTC, MrCat15352 requested changes

2024-05-09 17:16 UTC, MrCat15352 commented on code/modules/mob/observer/ghost/ghost.dm
> +// [CELADON-REMOVE OPISANIE_SCP]
Зачем оно тут? Если не удаляешь тут ничего удаляй его

2024-05-09 17:16 UTC, MrCat15352 commented on code/modules/mob/observer/ghost/ghost.dm
> +		//[CELADON-EDIT OPISANIE_SCP] -->
Не так... Вот так надо
`// [CELADON-EDIT] - OPISANIE_SCP`

2024-05-09 17:16 UTC, MrCat15352 commented on code/modules/mob/observer/ghost/ghost.dm
> +		//var/agreement = tgui_alert(src, "Warning! SCPs are likley to spend a long amount of time within their containment chamber and are not guaranteed to be let out![(selected_scp.SCP.metaFlags & SCP_R
в самом конце добавить надо `// CELADON-EDIT - ORIGINAL`

2024-05-09 17:16 UTC, MrCat15352 commented on code/modules/mob/observer/ghost/ghost.dm
> +		//var/agreement = tgui_alert(src, "Warning! SCPs are likley to spend a long amount of time within their containment chamber and are not guaranteed to be let out![(selected_scp.SCP.metaFlags & SCP_R
Получится вот так:
`//var/agreement = tgui_alert(src, "Warning! SCPs are likley to spend a long amount of time within their containment chamber and are not guaranteed to be let out![(selected_scp.SCP.metaFlags & SCP_ROLEPLAY) ? " Additionally, this is a roleplay oriented SCP. That means you are expected to behave like the SCP would in lore, and failing to do so would result in ban from playing roleplay SCPs." : ""]", "Are you sure?", list("Yes","No")) // CELADON-EDIT - ORIGINAL`

2024-05-09 17:16 UTC, MrCat15352 commented on code/modules/mob/observer/ghost/ghost.dm
> +		// <-- [CELADON-EDIT OPISANIE_SCP]
Не так, а вот так надо:
`// [/CELADON-EDIT]`

2024-05-09 17:16 UTC, MrCat15352 commented on mod_celadon/opisanie_scp/README.md
> +- `mods/_master_files/code/my_modular_override.dm`: `proc/overriden_proc`, `var/overriden_var`
Просто удали всё тут и оставь слово **Отсутствуют**

2024-05-09 17:16 UTC, MrCat15352 commented on mod_celadon/opisanie_scp/README.md
> +- `code/__defines/~mods/opisanie_scp.dm`: `OPISANIE_SCP_SPEED_MULTIPLIER`, `OPISANIE_SCP_SPEED_BASE`
Удали слово **отсутствуют**

2024-05-09 17:19 UTC, xhankaishi commented on code/modules/mob/observer/ghost/ghost.dm
> +// [CELADON-REMOVE OPISANIE_SCP]
я забыл убрать это  ЪУЪ

2024-05-09 17:19 UTC, xhankaishi commented on code/modules/mob/observer/ghost/ghost.dm
> +		//[CELADON-EDIT OPISANIE_SCP] -->
ЪУЪ

2024-05-09 17:23 UTC, xhankaishi commented on mod_celadon/opisanie_scp/README.md
> +- `code/__defines/~mods/opisanie_scp.dm`: `OPISANIE_SCP_SPEED_MULTIPLIER`, `OPISANIE_SCP_SPEED_BASE`
А там не отсутствует? Я туда ничего не добавлял

2024-05-09 17:40 UTC, MrCat15352 requested changes

2024-05-09 17:40 UTC, MrCat15352 commented on code/modules/mob/observer/ghost/ghost.dm
> +		//[CELADON-EDIT] OPISANIE_SCP -->
не так `//[CELADON-EDIT] OPISANIE_SCP -->`
а вот так `// [CELADON-EDIT] - OPISANIE_SCP`
Итак понятно что далее твой блок идет

2024-05-09 17:40 UTC, MrCat15352 commented on code/modules/mob/observer/ghost/ghost.dm
> +		// <-- [CELADON-EDIT] OPISANIE_SCP
не так `// <-- [CELADON-EDIT] OPISANIE_SCP`
а вот так `// [/CELADON-EDIT]`

2024-05-09 17:45 UTC, MrCat15352 requested changes

2024-05-09 17:45 UTC, MrCat15352 commented on code/modules/mob/observer/ghost/ghost.dm
> +		// [CELADON-EDIT] OPISANIE_SCP
Не вот так `// [CELADON-EDIT] OPISANIE_SCP`
а вот так `// [CELADON-EDIT] - OPISANIE_SCP`

2024-05-09 17:45 UTC, MrCat15352 commented on code/modules/mob/observer/ghost/ghost.dm
> +		// [/CELADON-EDIT] OPISANIE_SCP
Не вот так `// [/CELADON-EDIT] OPISANIE_SCP`
а вот так `// [/CELADON-EDIT]`

2024-05-09 17:50 UTC, MrCat15352 approved these changes

2024-05-09 17:50 UTC, merged