New scientist`s job names
CeladonSS13/Foundation-19 pull request #64
Opened 2024-05-08 19:12 UTC by quary01

ПР делает что-то умное. Добавлены новые названия для профессий ученых/исследователей, в зависимости от их научной дисциплины.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2024-05-08 19:42 UTC, MrCat15352 commented on code/game/jobs/job/research.dm
> +	alt_titles = list("Junior Biologist", "Junior Xenoarcheologist", "Junior Botanist", "Assistant Researcher", "Research Assistant", "Research Intern", "Junior Researcher")
Ну что же, уважаемый, начнем по порядку. Ваш код не соответствует минимальным требованиям модульности

2024-05-08 19:43 UTC, MrCat15352 requested changes

2024-05-08 19:43 UTC, MrCat15352 commented on code/game/jobs/job/research.dm
> +	alt_titles = list("Junior Biologist", "Junior Xenoarcheologist", "Junior Botanist", "Assistant Researcher", "Research Assistant", "Research Intern", "Junior Researcher")
Для начала прочитайте README.md в папке mod_celadon

2024-05-08 20:41 UTC, quary01 commented
Понял, принял. Перепишу код в ближайшее время.

2024-05-10 15:15 UTC, quary01 commented
Переделал модификацию под условия модульного кода, залью через другой пр, этот закрываю.

2024-05-10 15:15 UTC, closed without merging