New ungoc sprites
CeladonSS13/Foundation-19 pull request #93
Opened 2024-06-02 13:34 UTC by quary01

ПР делает что-то умное - заменен спрайт флага ГОК для патча ГОК на броню. 
Позже, возможно поменяю другие спрайты.

- [x] Pull Request полностью завершен, мне не нужна помощь чтобы его закончить.
- [x] Я внимательно прочитал все свои изменения и багов в них не нашел.
- [x] Я запускал сервер со своими изменениями локально и все протестировал.

2024-06-04 21:54 UTC, MrCat15352 requested changes

2024-06-04 21:54 UTC, MrCat15352 commented on mod_celadon/new_ungoc_sprites/_new_ungoc_sprites.dm
> +/datum/modpack/example/pre_initialize()
Убрать, если не нужно что-то инициализировать до или во время или после пака

2024-06-04 21:54 UTC, MrCat15352 commented on mod_celadon/new_ungoc_sprites/_new_ungoc_sprites.dme
> +#define MODPACK_NEW_UNGOC_SPRITES
```
#ifndef MODPACK_CELADON_EXAMPLE
#define MODPACK_CELADON_EXAMPLE
```

Твой код

`#endif`

А где проверки???

2024-06-04 21:54 UTC, MrCat15352 commented on tgui/yarn.lock
> -"axios@npm:^0.28.0":
это твоих рук дел?

2024-06-05 11:06 UTC, quary01 commented on tgui/yarn.lock
> -"axios@npm:^0.28.0":
не знаю откуда это появилось. Уберу в ближайшее время.

2024-06-05 11:06 UTC, quary01 commented on mod_celadon/new_ungoc_sprites/_new_ungoc_sprites.dm
> +/datum/modpack/example/pre_initialize()
Будет убрано

2024-06-06 07:38 UTC, MrCat15352 approved these changes

2024-06-06 07:38 UTC, merged